# change the followings to match your Github username and repo name
baseurl: "/herodian-temple" # the name of your github repo
url: "https://revnhill.github.io/herodian-temple/" # the url of your github pages (change BCDigSchol to your username)

# site information used in page title, meta data etc.
title: The Jerusalem Temple in the Time of Jesus
description: 3D modeling of the Second Temple as constructed under Herod the Great 29 B.C.E. - 70 C.E., with historical and religious background 

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: History
    submenu:
      - title: Hebrew Bible
        link: hebrewbible
      - title: Second Temple 
        link: secondtemple
      - title: Islamic Holy Sites
        link: islamic
  - title: Herodian Temple
    submenu:
      - title: Primary Sources
        link: methods
      - title: Features
        link: featuresmount
      - title: Temple Location
        link: location
  - title: About
    submenu:
      - title: This Project
        link: about 
      - title: Bibliography
        link: biblio

   
# sets whether a search bar appears on the site header
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: CC BY-NC License
footer-submessage:  By Rev. Natalie Hill, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: //G-JQHZN24CWS

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
